const fetch = require('node-fetch')
const {
  RESPONSE_CODES,
  RESPONSE_MSG
} = require('../constants')

const API_URL = 'https://api.anthropic.com'
const API_TOKEN = process.env.ANTHROPIC_API_TOKEN
const ANTHROPIC_VERSION = '2023-06-01'

exports.handleChatMessages = async (req, res) => {
  try {
    /* Send the user's messages to the OpenAI API
    The API will respond with a message generated by the model */
    const response = await fetch(`${API_URL}/v1/messages`, {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
        'X-API-Key': API_TOKEN,
        'anthropic-version': ANTHROPIC_VERSION
      },
      body: JSON.stringify({
        model: 'claude-3-haiku-20240307',
        system:
          'Roleplay as a text-based fantasy adventure game. Keep your responses to a couple sentences or less for a dynamic experience.',
        messages: req.body.messages,
        max_tokens: 200
      })
    })

    /* Parse the response from the API
    If the response is successful, send the assistant's reply to the user
    If the response is unsuccessful, send an error message */
    const data = await response.json()
    if (response.ok) {
      res.json({ message: data.content[0].text })
    } else {
      res
        .status(RESPONSE_CODES.SERVER_ERROR_500)
        .json({ error: RESPONSE_MSG.SERVER_ERROR_500 })
    }
  } catch (error) {
    console.error('Error POSTing chat message! ' + error)
    res
      .status(RESPONSE_CODES.SERVER_ERROR_500)
      .json({ error: RESPONSE_MSG.SERVER_ERROR_500 })
  }
}
